// message-exception.config.ts
export const Messages = {
  USER_NOT_FOUND: "User not found",
  USER_INVALID_CREDENTIAL: "Invalid credentials",
  USER_IN_ACTIVE: "Account is deactivated",
  USER_UNAUTHORIZATION: "Unauthorized",
  USER_NOT_VERIFIED: "Account is not verified! Please check mail.",
  USER_ALREADY_EXIST: "User with this email already exists",
  EMAIL_ALREADY_VERIFY: "Email already verified before",
  EMAIL_VERIFY_SUCCESS: "Email verify success",
  VERIFY_TOKEN_EXPIRED: "Verify token invalid or expired",
  EMAIL_VERIFICATION_SEND_SUCCESS: "Email verification send success! Check mail",
  EMAIL_VERIFICATION_RESEND_SUCCESS: "Email verification re-send success! Check mail",
  EMAIL_ALREADY_VERIFIED: "Email has already been verified.",
  EMAIL_VERIFICATION_SUCCESS: "Email verification successful.",
  EMAIL_VERIFICATION_FAILED: "Email verification failed.",
  PASSWORD_RESET_EMAIL_SENT: "Email reset password has been sent",
  PASSWORD_RESET_SUCCESS: "Password has been reset successfully",
  GOOGLE_AUTH_ERROR: "Google authentication error, please try again later",
  TOKEN_INVALID: "Token is invalid",
  TOKEN_EXPIRED: "Token has expired",
  TOKEN_ALREADY_USED: "Token is invalid or already used",
  CHART_UPDATE_SUCCESS: "chart_update_success_message",
  // Subscription plan messages
  SUBSCRIPTION_PLAN_CREATE_SUCCESS: "Subscription plan created successfully",
  SUBSCRIPTION_PLAN_UPDATE_SUCCESS: "Subscription plan updated successfully",
  SUBSCRIPTION_PLAN_DELETE_SUCCESS: "Subscription plan deleted successfully",
  // Subscription limit messages
  DATASET_LIMIT_EXCEEDED: "You have reached the maximum number of datasets allowed for your subscription plan",
  CHART_LIMIT_EXCEEDED: "You have reached the maximum number of charts allowed for your subscription plan",
  FILE_SIZE_LIMIT_EXCEEDED: "You have exceeded the maximum file size allowed for your subscription plan",
  AI_REQUEST_LIMIT_EXCEEDED: "You have exceeded the maximum number of AI requests allowed for your subscription plan",
  NO_SUBSCRIPTION_PLAN: "No subscription plan found for your account",
};